# Generated by Django 4.2.1 on 2023-05-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('0', 'none'), ('1', 'very bad'), ('2', 'bad'), ('3', 'meh'), ('4', 'fine'), ('5', 'okay'), ('6', 'good'), ('7', 'very good')], max_length=1)),
                ('notes', models.CharField(max_length=500)),
                ('emotions', models.CharField(choices=[('1', 'Happy'), ('2', 'Excited'), ('3', 'Proud'), ('4', 'Relaxed'), ('5', 'Laughative'), ('6', 'Neutral'), ('7', 'Sad'), ('8', 'Angry'), ('9', 'Annoyed'), ('10', 'Depressed'), ('11', 'Stressed'), ('12', 'Tired'), ('13', 'Anxious'), ('14', 'Lonely')], max_length=2)),
                ('date', models.DateField()),
            ],
        ),
    ]
