# Generated by Django 4.2.1 on 2023-06-07 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Calendar', '0002_day_user_alter_day_emotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='emotions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Happy'), ('2', 'Excited'), ('3', 'Proud'), ('4', 'Relaxed'), ('5', 'Laughative'), ('6', 'Neutral'), ('7', 'Sad'), ('8', 'Angry'), ('9', 'Annoyed'), ('10', 'Depressed'), ('11', 'Stressed'), ('12', 'Tired'), ('13', 'Anxious'), ('14', 'Lonely')], max_length=100),
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Calendar.month'),
        ),
    ]
