# Generated by Django 4.2.1 on 2023-06-07 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0003_alter_day_emotions_month_day_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='user',
        ),
    ]
