# Generated by Django 4.2.1 on 2023-06-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0005_month_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='month',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='month',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
