# Generated by Django 4.2.1 on 2023-06-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0006_month_month_month_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
